---
name: 'Common preparation steps'
description: 'Check out code & install node.js, hugo and npm dependencies'
branding:
  icon: 'layers'
  color: 'green'
inputs:
  submodules:
    description: 'Should we checkout git submodules?'
    default: false
  nodejs:
    description: 'Should we install node.js and install npm dependencies?'
    default: true
  hugo_version:
    description: 'Version of hugo to install'
    default: 'v0.139.4'
runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.submodules }}  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Install hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ inputs.hugo_version }}
        extended: true
    - if: ${{ inputs.nodejs == 'true' }}
      name: Install node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - if: ${{ inputs.nodejs == 'true' }}
      name: Install npm dependencies
      run: npm i
      shell: bash
