---
name: 'Common preparation steps'
description: 'Check out code & install node.js, hugo and npm dependencies'
branding:
  icon: 'layers'
  color: 'green'
runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        # Fetch all history for .GitInfo and .Lastmod
        fetch-depth: 0
    - name: Install node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true
    - name: Install npm dependencies
      run: npm i
      shell: bash
